
DROP PROCEDURE IF EXISTS CHECK_NHANVIEN;
GO
DROP PROCEDURE IF EXISTS CHUYEN_NHANVIEN;
GO
-- hÀM CHECK NHANVIEN CỦA CHI NHÁNH
CREATE PROC CHECK_NHANVIEN
    @MANV CHAR(5),
    @MACN CHAR(5),
	@result int OUTPUT
AS
BEGIN
    -- Kiểm tra đối số đầu vào
    IF @MANV IS NULL OR @MACN IS NULL
    BEGIN
		SET @RESULT = 0
        RETURN @RESULT; -- Hoặc trả về một giá trị khác để biểu thị lỗi
    END

    -- Kiểm tra chi nhánh và nhân viên tương ứng
    IF @MACN = 'CN001'
    BEGIN
        IF NOT EXISTS (SELECT * FROM QuanLyBanHang_CN001.DBO.NHANVIEN WHERE MaNV = @MANV)
        BEGIN
			SET @RESULT = 0
            RETURN @RESULT; -- Trả về 0 nếu không tìm thấy nhân viên
        END
		SET @RESULT = 1
		RETURN @RESULT
    END
    ELSE IF @MACN = 'CN002'
    BEGIN
        IF NOT EXISTS (SELECT * FROM QuanLyBanHang_CN002.DBO.NHANVIEN WHERE MaNV = @MANV)
        BEGIN
			SET @RESULT = 0
				RETURN @RESULT; -- Trả về 0 nếu không tìm thấy nhân viên
        END
			SET @RESULT =2
		RETURN @RESULT
    END
    ELSE IF @MACN = 'CN003'
    BEGIN
        IF NOT EXISTS (SELECT * FROM QuanLyBanHang_CN003.DBO.NHANVIEN WHERE MaNV = @MANV)
        BEGIN
		SET @RESULT = 0
            RETURN @RESULT; -- Trả về 0 nếu không tìm thấy nhân viên
        END
		SET @RESULT =3
		RETURN @RESULT
    END

	SET @RESULT = 0
    -- Trả về 1 nếu nhân viên tồn tại trong chi nhánh
	RETURN @RESULT
END

GO

-- hÀM CHUYỂN NHÂN VIÊN
CREATE PROCEDURE CHUYEN_NHANVIEN
    @MNV1 CHAR(5),
    @MNV2 CHAR(5),
    @CN1 CHAR(5),
    @CN2 CHAR(5)
AS
BEGIN
	DECLARE @CHECK1 INT, @CHECK2 INT
	DECLARE  @MANV1 CHAR(5) ,@HO1 NVARCHAR(50) ,@TEN1 NVARCHAR(50) ,@NGAYSINH1 DATE,@MUCLUONG1 DECIMAL(15, 2),
		@DC_THUONGTRU1 NVARCHAR(255),
		@DC_LIENLAC1 NVARCHAR(255),
		@SOCMND1 CHAR(12),
		@MACN1 CHAR(5),
		@LOGINNAME1 NVARCHAR(50) ,
		@PASSWORD1 NVARCHAR(50)
	
	EXEC DBO.CHECK_NHANVIEN @MNV1, @CN1, @Check1 OUTPUT;
	EXEC DBO.CHECK_NHANVIEN @MNV2, @CN2, @Check2 OUTPUT;

	-- CHECK ĐIỀU KIỆN CHÍNH XÁC
	IF @CHECK1 = 0
	BEGIN
		RETURN 'KHÔNG TRUYỀN ĐÚNG MÃ NV HOẶC CHI NHÁNH ĐỐI VỚI NHAN VIEN 1'
	END

	IF @CHECK2 = 0
	BEGIN
		RETURN 'KHÔNG TRUYỀN ĐÚNG MÃ NV HOẶC CHI NHÁNH ĐỐI VỚI NHAN VIEN 2'
	END
	
	IF @CHECK1 = 1 -- nẾU CHECK1 LÀ Ở DATABASE NÀO THÌ ĐƯA NÓ VÀO DATABASE NÀO THÌ LẤY DATA CỦA DATABASE ĐÓ
	SELECT @MANV1 = MANV, @HO1 =HO, @TEN1= TEN, @NGAYSINH1 = NGAYSINH, 
	@MUCLUONG1= MUCLUONG, @DC_THUONGTRU1 = DC_THUONGTRU, @DC_LIENLAC1 = DC_LIENLAC, 
	@SOCMND1 = SOCMND, @MACN1 = MACN, @LOGINNAME1 = LOGINNAME, @PASSWORD1 = PASSWORD
	FROM QuanLyBanHang_CN001.DBO.NHANVIEN WHERE MANV = @MNV1

	IF @CHECK1 = 2
	SELECT @MANV1 = MANV, @HO1 =HO, @TEN1= TEN, @NGAYSINH1 = NGAYSINH, 
	@MUCLUONG1= MUCLUONG, @DC_THUONGTRU1 = DC_THUONGTRU, @DC_LIENLAC1 = DC_LIENLAC, 
	@SOCMND1 = SOCMND, @MACN1 = MACN, @LOGINNAME1 = LOGINNAME, @PASSWORD1 = PASSWORD
	FROM QuanLyBanHang_CN002.DBO.NHANVIEN WHERE MANV = @MNV1

	IF @CHECK1 = 3
	SELECT @MANV1 = MANV, @HO1 =HO, @TEN1= TEN, @NGAYSINH1 = NGAYSINH, 
	@MUCLUONG1= MUCLUONG, @DC_THUONGTRU1 = DC_THUONGTRU, @DC_LIENLAC1 = DC_LIENLAC, 
	@SOCMND1 = SOCMND, @MACN1 = MACN, @LOGINNAME1 = LOGINNAME, @PASSWORD1 = PASSWORD
	FROM QuanLyBanHang_CN003.DBO.NHANVIEN WHERE MANV = @MNV1

	--- LẤY DATA CHO NV THỨ 2
	DECLARE  @MANV2 CHAR(5) ,@HO2 NVARCHAR(50) ,@TEN2 NVARCHAR(50) ,@NGAYSINH2 DATE,@MUCLUONG2 DECIMAL(15, 2),
		@DC_THUONGTRU2 NVARCHAR(255),
		@DC_LIENLAC2 NVARCHAR(255),
		@SOCMND2 CHAR(12),
		@MACN2 CHAR(5),
		@LOGINNAME2 NVARCHAR(50) ,
		@PASSWORD2 NVARCHAR(50)

	IF @CHECK2 = 1
	SELECT @MANV2 = MANV, @HO2 =HO, @TEN2= TEN, @NGAYSINH2= NGAYSINH, 
	@MUCLUONG2= MUCLUONG, @DC_THUONGTRU2 = DC_THUONGTRU, @DC_LIENLAC2 = DC_LIENLAC, 
	@SOCMND2 = SOCMND, @MACN2 = MACN, @LOGINNAME2= LOGINNAME, @PASSWORD2 = PASSWORD
	FROM QuanLyBanHang_CN001.DBO.NHANVIEN WHERE MANV = @MNV2

	IF @CHECK2 = 2
	SELECT @MANV2 = MANV, @HO2 =HO, @TEN2= TEN, @NGAYSINH2= NGAYSINH, 
	@MUCLUONG2= MUCLUONG, @DC_THUONGTRU2 = DC_THUONGTRU, @DC_LIENLAC2 = DC_LIENLAC, 
	@SOCMND2 = SOCMND, @MACN2 = MACN, @LOGINNAME2= LOGINNAME, @PASSWORD2 = PASSWORD
	FROM QuanLyBanHang_CN002.DBO.NHANVIEN WHERE MANV = @MNV2

	IF @CHECK2 = 3
	SELECT @MANV2 = MANV, @HO2 =HO, @TEN2= TEN, @NGAYSINH2= NGAYSINH, 
	@MUCLUONG2= MUCLUONG, @DC_THUONGTRU2 = DC_THUONGTRU, @DC_LIENLAC2 = DC_LIENLAC, 
	@SOCMND2 = SOCMND, @MACN2 = MACN, @LOGINNAME2= LOGINNAME, @PASSWORD2 = PASSWORD
	FROM QuanLyBanHang_CN003.DBO.NHANVIEN WHERE MANV = @MNV2


	
	-- ADD VÀO CÁC BẢNG DATA VÀO MNV1 VÀO MV2
	IF @CHECK2 = 1
	BEGIN
		INSERT INTO QuanLyBanHang_CN001.DBO.NHANVIEN(MANV, HO, TEN, NGAYSINH, MUCLUONG, DC_THUONGTRU, DC_LIENLAC, SOCMND, MACN, LOGINNAME, PASSWORD)
		VALUES  (@MANV1, @HO1, @TEN1, @NGAYSINH1, @MUCLUONG1, @DC_THUONGTRU1, @DC_LIENLAC1, @SOCMND1,'CN001', @LOGINNAME1, @PASSWORD1);
	END

	IF @CHECK2 = 2
	BEGIN
		INSERT INTO QuanLyBanHang_CN002.DBO.NHANVIEN(MANV, HO, TEN, NGAYSINH, MUCLUONG, DC_THUONGTRU, DC_LIENLAC, SOCMND, MACN, LOGINNAME, PASSWORD)
		VALUES  (@MANV1, @HO1, @TEN1, @NGAYSINH1, @MUCLUONG1, @DC_THUONGTRU1, @DC_LIENLAC1, @SOCMND1,'CN002', @LOGINNAME1, @PASSWORD1);
	END
	IF @CHECK2 = 3
	BEGIN
		INSERT INTO QuanLyBanHang_CN003.DBO.NHANVIEN(MANV, HO, TEN, NGAYSINH, MUCLUONG, DC_THUONGTRU, DC_LIENLAC, SOCMND, MACN, LOGINNAME, PASSWORD)
		VALUES  (@MANV1, @HO1, @TEN1, @NGAYSINH1, @MUCLUONG1, @DC_THUONGTRU1, @DC_LIENLAC1, @SOCMND1,'CN003', @LOGINNAME1, @PASSWORD1);
	END

	IF @CHECK1 = 1
		DELETE FROM QuanLyBanHang_CN001.dbo.NHANVIEN
		WHERE MANV = @MNV1;

	IF @CHECK1 = 2
		DELETE FROM QuanLyBanHang_CN002.dbo.NHANVIEN
		WHERE MANV = @MNV1;
	IF @CHECK1 = 3
		DELETE FROM QuanLyBanHang_CN003.dbo.NHANVIEN
		WHERE MANV = @MNV1;


	--- ADD CÁC BẢNG DATA VÀO MANV 2 SANG manv 1
	IF @CHECK1= 1
	BEGIN
		INSERT INTO QuanLyBanHang_CN001.DBO.NHANVIEN(MANV, HO, TEN, NGAYSINH, MUCLUONG, DC_THUONGTRU, DC_LIENLAC, SOCMND, MACN, LOGINNAME, PASSWORD)
		VALUES  (@MANV2, @HO2, @TEN2, @NGAYSINH2, @MUCLUONG2, @DC_THUONGTRU2, @DC_LIENLAC2, @SOCMND2,'CN001', @LOGINNAME2, @PASSWORD2);
	END

	IF @CHECK1 = 2
	BEGIN
		INSERT INTO QuanLyBanHang_CN002.DBO.NHANVIEN(MANV, HO, TEN, NGAYSINH, MUCLUONG, DC_THUONGTRU, DC_LIENLAC, SOCMND, MACN, LOGINNAME, PASSWORD)
		VALUES  (@MANV2, @HO2, @TEN2, @NGAYSINH2, @MUCLUONG2, @DC_THUONGTRU2, @DC_LIENLAC2, @SOCMND2,'CN001', @LOGINNAME2, @PASSWORD2);
	END
	IF @CHECK1 = 3
	BEGIN
		INSERT INTO QuanLyBanHang_CN003.DBO.NHANVIEN(MANV, HO, TEN, NGAYSINH, MUCLUONG, DC_THUONGTRU, DC_LIENLAC, SOCMND, MACN, LOGINNAME, PASSWORD)
		VALUES  (@MANV2, @HO2, @TEN2, @NGAYSINH2, @MUCLUONG2, @DC_THUONGTRU2, @DC_LIENLAC2, @SOCMND2,'CN001', @LOGINNAME2, @PASSWORD2);
	END

	IF @CHECK2 = 1
		DELETE FROM QuanLyBanHang_CN001.dbo.NHANVIEN
		WHERE MANV = @MNV2;

	IF @CHECK2 = 2
		DELETE FROM QuanLyBanHang_CN002.dbo.NHANVIEN
		WHERE MANV = @MNV2;
	IF @CHECK2 = 3
		DELETE FROM QuanLyBanHang_CN003.dbo.NHANVIEN
		WHERE MANV = @MNV2;
 
	 

END;
go

declare  @MNV1 CHAR(5),@MNV2 CHAR(5),
    @CN1 CHAR(5),
    @CN2 CHAR(5)
set @MNV1 = 'NV005'
SET @MNV2 = 'NV006'
SET @CN1 = 'CN002'
SET @CN2 = 'CN003'
exec CHUYEN_NHANVIEN @MNV1, @MNV2, @CN1, @CN2;